// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBx4cuzLQsUIv_KNjxiW39_D6E05scWgpY',
    appId: '1:947141844718:web:634d651b76eb490d485dff',
    messagingSenderId: '947141844718',
    projectId: 'bigtable-connect',
    authDomain: 'bigtable-connect.firebaseapp.com',
    databaseURL: 'https://bigtable-connect-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bigtable-connect.firebasestorage.app',
    measurementId: 'G-5TRCLQFW2N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAxFwGDwZep_KqlLQT0Uo0PF4cGlPHgPw',
    appId: '1:947141844718:android:1365a31949fbf483485dff',
    messagingSenderId: '947141844718',
    projectId: 'bigtable-connect',
    databaseURL: 'https://bigtable-connect-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bigtable-connect.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAixhYlyc8CYS0tf0fbTpC_hBy19mBpl1I',
    appId: '1:947141844718:ios:7840fd429e7b2f36485dff',
    messagingSenderId: '947141844718',
    projectId: 'bigtable-connect',
    databaseURL: 'https://bigtable-connect-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bigtable-connect.firebasestorage.app',
    androidClientId: '947141844718-vgf9vhu2uqi6oc1fb0ls79gspqj95e30.apps.googleusercontent.com',
    iosClientId: '947141844718-5mkjjj944vrpm5dnqbli6kvvmncdvn05.apps.googleusercontent.com',
    iosBundleId: 'io.github.bigtableconnect.bigtableConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAixhYlyc8CYS0tf0fbTpC_hBy19mBpl1I',
    appId: '1:947141844718:ios:7840fd429e7b2f36485dff',
    messagingSenderId: '947141844718',
    projectId: 'bigtable-connect',
    databaseURL: 'https://bigtable-connect-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bigtable-connect.firebasestorage.app',
    androidClientId: '947141844718-vgf9vhu2uqi6oc1fb0ls79gspqj95e30.apps.googleusercontent.com',
    iosClientId: '947141844718-5mkjjj944vrpm5dnqbli6kvvmncdvn05.apps.googleusercontent.com',
    iosBundleId: 'io.github.bigtableconnect.bigtableConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBx4cuzLQsUIv_KNjxiW39_D6E05scWgpY',
    appId: '1:947141844718:web:602bb962abe9e987485dff',
    messagingSenderId: '947141844718',
    projectId: 'bigtable-connect',
    authDomain: 'bigtable-connect.firebaseapp.com',
    databaseURL: 'https://bigtable-connect-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bigtable-connect.firebasestorage.app',
    measurementId: 'G-JFQG5ZJG51',
  );

}